### PR TITLE
Delete all test apps

### PR DESCRIPTION
**Pull request by tfussell**
Catalog pulls and pushes are getting very slow in CI because this is so large. I think it's time to clear it out.

### CODE REVIEW

**Review by kopiczko — APPROVED** [review]
I'm fine with that. Maybe it would be good to have some sort of job that leaves only tarballs that are not older than one week. I'm not able to review this because GH is too slow for so many files. I hope `index.yaml` is ok.

**Comment by TheoBrigitte** [comment]
> I'm fine with that. Maybe it would be good to have some sort of job that leaves only tarballs that are not older than one week. I'm not able to review this because GH is too slow for so many files. I hope `index.yaml` is ok.

git doesn't store file date. So we can't find which tarball are older.

**Comment by kopiczko** [comment]
We can check modification date or this https://raw.githubusercontent.com/giantswarm/control-plane-test-catalog/master/index.yaml (it has `created:` key).

**Review by TheoBrigitte — APPROVED** [review]
Nice!

**Pull request merged**
